#!/usr/bin/env python3
"""
Bluestock Mutual Fund Analytics — Email Report Generator (Bonus B5)
===================================================================
Generates a weekly HTML report with performance metrics and charts.

Usage:
    python scripts/email_report_generator.py
"""

import sys
import logging
from pathlib import Path
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import base64
from io import BytesIO

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger("EmailReport")

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = PROJECT_ROOT / "data" / "db" / "bluestock_mf.db"
OUTPUT_DIR = PROJECT_ROOT / "reports"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def generate_report():
    logger.info("Generating Weekly Email Report...")
    
    if not DB_PATH.exists():
        logger.error(f"Database not found at {DB_PATH}")
        sys.exit(1)
        
    conn = sqlite3.connect(DB_PATH)
    
    # Get top funds
    query = """
    SELECT f.scheme_name, f.sub_category, p.return_3yr_pct, p.sharpe_ratio
    FROM dim_fund f
    JOIN fact_performance p ON f.amfi_code = p.amfi_code
    ORDER BY p.return_3yr_pct DESC
    LIMIT 10
    """
    top_funds = pd.read_sql(query, conn)
    
    # Get AUM summary
    aum_query = """
    SELECT fund_house, SUM(aum_crore) as total_aum
    FROM fact_aum
    WHERE date = (SELECT MAX(date) FROM fact_aum)
    GROUP BY fund_house
    ORDER BY total_aum DESC
    LIMIT 5
    """
    top_amcs = pd.read_sql(aum_query, conn)
    conn.close()
    
    # Generate a chart and convert to base64
    plt.figure(figsize=(8, 4))
    plt.bar(top_amcs['fund_house'], top_amcs['total_aum'] / 100000, color='#0056b3')
    plt.title('Top 5 AMCs by AUM (Lakh Crore)')
    plt.ylabel('AUM (Lakh Cr)')
    plt.xticks(rotation=15, ha='right')
    plt.tight_layout()
    
    img_buffer = BytesIO()
    plt.savefig(img_buffer, format='png')
    img_buffer.seek(0)
    img_str = base64.b64encode(img_buffer.read()).decode('utf-8')
    
    # Create HTML
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; color: #333; }}
            .container {{ width: 80%; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 5px; }}
            .header {{ background-color: #0056b3; color: white; padding: 10px; text-align: center; border-radius: 5px 5px 0 0; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
            th {{ background-color: #f2f2f2; }}
            .footer {{ margin-top: 20px; font-size: 12px; color: #777; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>Bluestock Mutual Fund Weekly Summary</h2>
            </div>
            
            <h3>Top Performing Funds (3Y CAGR)</h3>
            {top_funds.to_html(index=False)}
            
            <h3>Industry Snapshot</h3>
            <img src="data:image/png;base64,{img_str}" alt="AUM Chart" style="width:100%; max-width:600px;">
            
            <div class="footer">
                <p>Automated report generated by Bluestock Analytics Engine.</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    # Save report
    report_path = OUTPUT_DIR / "Weekly_Summary.html"
    report_path.write_text(html_content)
    
    logger.info(f"Report generated successfully: {report_path}")

if __name__ == "__main__":
    generate_report()
